apply plugin: 'com.android.application'

def getGitCommitHash = { ->
    try {
        def stdout = new ByteArrayOutputStream()
        exec {
            commandLine 'git', 'rev-parse', '--short', 'HEAD'
            standardOutput = stdout
        }
        return stdout.toString().trim()
    } catch (ignored) {
        return "nogit"
    }
}

android {
    compileSdkVersion 35
    defaultConfig {
        applicationId "nldoko.game.v2"
        minSdkVersion 21
        targetSdkVersion 35
        versionCode 15
        versionName "4.0.0"
        def commitHash = getGitCommitHash()

        // SemVer-Format: 4.0.0+a1b2c3d
        def fullVersionDisplay = "${versionName}+${commitHash}"

        resValue "string", "app_version", fullVersionDisplay
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    namespace 'nldoko.game'
    applicationVariants.configureEach { variant ->
        variant.outputs.configureEach { output ->
            def appName = "Doppelkopf-2.0"
            def versionName = variant.versionName
            def buildType = variant.buildType.name
            def commitHash = getGitCommitHash()

            // e.g. Doppelkopf-2.0_v4.0.0+debug_a1b2c3d.apk
            def newApkName = "${appName}_v${versionName}+${buildType}_${commitHash}.apk"
            outputFileName = newApkName
        }
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    androidTestImplementation('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    implementation 'androidx.core:core-ktx:1.9.0'
    implementation 'androidx.appcompat:appcompat:1.6.1'
    testImplementation 'junit:junit:4.12'
    implementation("com.mikepenz:materialdrawer:6.1.2")
    implementation "androidx.recyclerview:recyclerview:1.0.0"
    implementation "androidx.annotation:annotation:1.0.0"
    implementation "com.google.android.material:material:1.0.0"
    implementation "androidx.constraintlayout:constraintlayout:1.1.3"
}
